// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sina.Mocut.Backend.Infrastructure.Database;

#nullable disable

namespace Sina.Mocut.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(MocutDB))]
    [Migration("20231012144229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sina.Mocut.Backend.Core.Entitis.Barber", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneNumber");

                    b.ToTable("barbers");
                });

            modelBuilder.Entity("Sina.Mocut.Backend.Core.Entitis.BarberOwner", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Username");

                    b.ToTable("barberOwners");
                });

            modelBuilder.Entity("Sina.Mocut.Backend.Core.Entitis.Counter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("counters");
                });

            modelBuilder.Entity("Sina.Mocut.Backend.Core.Entitis.Customer", b =>
                {
                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Phonenumber");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Sina.Mocut.Backend.Core.Entitis.SystemManagement", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("systemManagements");
                });
#pragma warning restore 612, 618
        }
    }
}
